# Generated by Django 4.1.7 on 2023-03-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprodile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProdile',
            new_name='UserProfile',
        ),
    ]
